[project]
name = "pytunetag"
version = "0.1.0"
description = "A Python library to automatically detect and modify music genres for mp3 files."
requires-python = ">=3.12"

dependencies = [
    "torch",
    "numpy",
    "pydub",
    "mutagen"
]

[project.scripts]
pytunetag = "src.cli:cli"